version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/dice_summon
    volumes:
      - .:/app
    restart: always
    networks:
      - dice_net

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dice_summon
    networks:
      - dice_net

volumes:
  mongo-data:

networks:
  dice_net:
    driver: bridge
